# Generated by Django 3.0.3 on 2020-08-20 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200819_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime_recup', models.DateTimeField(verbose_name='date de récupération')),
                ('dateTime_livraison', models.DateTimeField(verbose_name='date de livraison')),
                ('adresse_livraison', models.TextField(max_length=500, verbose_name='adresse de livraison')),
                ('tel_livraison', models.IntegerField(max_length=10, verbose_name='numéro de téléphone du client')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('prix', models.IntegerField(verbose_name='prix commande')),
                ('etat', models.PositiveSmallIntegerField(choices=[(1, 'Nouvelle'), (2, 'en attente'), (3, 'réponse'), (4, 'validée'), (5, 'suppriméée')])),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Fournisseur', verbose_name='fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=200, verbose_name='code de validation')),
                ('prix', models.IntegerField(verbose_name='prix livraison')),
                ('etat', models.PositiveSmallIntegerField(choices=[(1, 'acceptée'), (2, 'en cours'), (3, 'en livraison'), (4, 'terminée')])),
                ('fd_paid', models.BooleanField(default=False)),
                ('fournisseur_paid', models.BooleanField(default=False)),
                ('Commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commandes.Commande', verbose_name='commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
            ],
        ),
    ]
