# Generated by Django 3.0.3 on 2020-08-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200819_2251'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='feedback',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.Fournisseur', verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='Commande',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='commandes.Commande', verbose_name='commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='code',
            field=models.TextField(editable=False, max_length=200, verbose_name='code de validation'),
        ),
    ]
