# Generated by Django 3.0.3 on 2020-08-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_auto_20200820_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='tel_livraison',
            field=models.IntegerField(verbose_name='numéro de téléphone du client'),
        ),
    ]
