# Generated by Django 3.0.3 on 2020-08-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_auto_20200820_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='Commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commandes.Commande', verbose_name='commande'),
        ),
    ]
