# Generated by Django 3.0.3 on 2020-08-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200819_2251'),
        ('commandes', '0004_auto_20200820_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Fournisseur', verbose_name='fournisseur'),
        ),
    ]
