# Generated by Django 3.0.3 on 2020-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'livreur'), (2, 'fournisseur'), (3, 'modérateur'), (4, 'administrateur')], null=True),
        ),
    ]
