# Generated by Django 3.0.3 on 2020-08-19 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200818_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.TextField(max_length=200, verbose_name='entreprise')),
                ('numTel', models.IntegerField(max_length=10, verbose_name='numéro de téléphone')),
                ('adresse', models.TextField(max_length=500, verbose_name='adresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
