# Generated by Django 3.0.3 on 2020-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('email_from', models.EmailField(max_length=254, verbose_name='source')),
            ],
        ),
    ]
